import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { Header } from "../components/Header"

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>SmartSync App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        {/* <Content /> */}
      </main>
    </>
  );
}
