import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

import { Header } from "../components/Header"

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // const users = api.user.getAll.useQuery();

  // to use mutation
  // 1. call useMutation
  const createUser = api.user.createUser.useMutation({});
  // 2. call mutate with data
  // this throwing error in the vercel for somereason
  // createUser.mutate({
  //   email: 'wei@lia.com' + Math.random(),
  //   name: 'sillynutz'
  // });  

  return (
    <>
      <Head>
        <title>SmartSync App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
        {/* <Content /> */}
        <div>{JSON.stringify(users)}</div>
      </main>
    </>
  );
}

